# Rubocop rules explanation:
#  https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/bundle
    - spec

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/ExpandPathArguments:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/WordArray:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 150
